# The base URL of your Gitea instance
gitea_url = "https://gitmirror.hak8or.com"

# Your Gitea API key (generate one from User Settings -> Applications)
api_key = "API_KEY_GOES_HERE"

# Optional: specify the owner username for all migrated repos
# If not specified, uses the user who owns the API key
repo_owner = "mirror_org"

# A list of remote git repositories to mirror.
repos = [
	{ url = "https://gitea.hak8or.com/hak8or/gitea_mirror.git" },
	{ rename = "cool_rename", url = "https://gitea.hak8or.com/hak8or/gitea_mirror.git" },
	{ rename = "cool_another_rename", url = "https://gitea.hak8or.com/hak8or/gitea_mirror.git" },
	{ url = "https://github.com/justcallmekoko/ESP32Marauder" }
]

# Optional: List of repository names to exclude from verification (if --verify-canfetch is used)
repos_exclude_verify = [
    { name = "ESP32Marauder", reason = "This repo is known to be flaky." },
    { name = "some-other-repo", reason = """
    This repo is very large and times out.
    We will fix this later.
    """ }
]

organizations = [
	{ url = "https://gitea.hak8or.com/mirrors" },
]
